Region.create( name: "ภาคเหนือ" )
Region.create( name: "ภาคตะวันออก" )
Region.create( name: "ภาคตะวันออกเฉียงเหนือ" )
Region.create( name: "ภาคกลาง" )
Region.create( name: "ภาคใต้" )
Region.create( name: "ภาคตะวันตก" )
Stage.create( name: "ระยะกล้า", min_day: 0, max_day: 14 )
Stage.create( name: "ระยะแตกกอ", min_day: 15, max_day: 28 )
Stage.create( name: "ระยะออกรวง", min_day: 29, max_day: 39 )
Stage.create( name: "ระยะตั้งท้อง", min_day: 40, max_day: 999 )
Stage.create( name: "25วัน", min_day: 0, max_day: 25 )
Stage.create( name: "50วัน", min_day: 26, max_day: 50 )
Stage.create( name: "75วัน", min_day: 51, max_day: 75 )
Ecology.create( name: "นาน้ำฝน" ) 
Ecology.create( name: "นาชลประทาน" )
AreaType.create( name: "ที่ลุ่น" )
AreaType.create( name: "ที่ดอน" )
Plantation.create( name: "ปักดำ" )
Plantation.create( name: "หว่าน" )
Plantation.create( name: "หยอด" )
SoilType.create( name: "ดินเหนียว" )
SoilType.create( name: "ดินร่วน" )
SoilType.create( name: "ดินทราย" )
ContentType.create( name: 'ระยะกล้า' )
ContentType.create( name: "ระยะแตกกอ" )
ContentType.create( name: "ระยะออกรวง" )
ContentType.create( name: "ระยะตั้งท้อง" )
ContentType.create( name: "การรักษา" )
ContentType.create( name: "การป้องกัน" )
ContentType.create( name: "ข่าว" )

Disease.read_disease_to_record

Content.read_content_to_record